- name: Switch graphics to uxa
  copy: src=20-intel.conf dest=/usr/share/X11/xorg.conf.d/20-intel.conf mode=0644
  sudo: yes
- name: Scaling (text)
  command: gsettings set org.gnome.desktop.interface text-scaling-factor 1
- name: Scaling (cursor size)
  command: gsettings set org.gnome.desktop.interface cursor-size 45
- name: Scaling (scale factor)
  command: 'gsettings set com.ubuntu.user-interface scale-factor "{''eDP1'': 15}"'
